// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fstyxfuyploifiouotni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzdHl4ZnV5cGxvaWZpb3VvdG5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1NTg1MTUsImV4cCI6MjA4NjEzNDUxNX0.TXG_GywmXlyNXxkIj_m6JKtQrJ8lDA9RJWN3HiyKmXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});